"""empty message

Revision ID: 5db9df03c885
Revises: 4515b1269be2
Create Date: 2022-06-29 13:35:18.331417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db9df03c885'
down_revision = '4515b1269be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rents', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rents', 'verified')
    # ### end Alembic commands ###
